//CONSTANTES, TYPEDEFS, ENUMS GLOBALES

// INCLUDES
#include <stdint.h>
#include <stdarg.h>
#include <stdlib.h>
#include <stdbool.h>
#include "disdrv.h"
#include "joydrv.h"
#include "termlib.h"

//DEFINES 
#define CANTFILS 16
#define CANTCOLS 16
#define VIVA 1
#define MUERTA 0
#define ENCENDIDA 1
#define APAGADA 0

// STRUCTURES AND ENUMS
typedef uint8_t action_t; //PLAY/PAUSE/UP/DOWN/LEFT/RIGHT/EXITGAME/EXITPROGRAM

typedef uint8_t mundo_t[16][16];

typedef uint8_t rpinr_t[5][3];

typedef struct {
    uint8_t estado; //1 si viva, 0 si muerta
    dcoord_t coords;
    uint8_t encendida; //1 si esta encendida, 0 si esta apagada
    uint8_t vidas;
    uint8_t nivel;
} rana_t;

enum player_action {NONE=0, PLAY, EXIT, UP, DOWN, LEFT, RIGHT, TOPSCORES}; //play-pause y exitgame-exitprgram se infiere por contexto
enum cell_state {STREET=0, CAR, TRUCK, WATER, LOG, SAFE, DEAD};

// GLOBAL VARIABLES
rana_t frog = {.estado=VIVA,.coords.x=8,.coords.y=15,.encendida=APAGADA,.vidas=2,.nivel='1'};
mundo_t world = {
    {DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD,DEAD},
    {DEAD,SAFE,SAFE,SAFE,DEAD,DEAD,SAFE,SAFE,DEAD,DEAD,SAFE,DEAD,DEAD,SAFE,SAFE,DEAD},
    {WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER},
    {LOG,LOG,LOG,WATER,WATER,WATER,WATER,WATER,LOG,LOG,WATER,WATER,WATER,WATER,WATER,WATER},
    {WATER,WATER,WATER,WATER,LOG,LOG,LOG,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER},
    {WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER},
    {WATER,LOG,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER},
    {WATER,WATER,WATER,WATER,WATER,WATER,WATER,LOG,LOG,LOG,LOG,WATER,WATER,WATER,WATER,WATER},
    {SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE},
    {STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET},
    {STREET,TRUCK,TRUCK,STREET,STREET,STREET,STREET,TRUCK,TRUCK,STREET,STREET,STREET,STREET,STREET,STREET,STREET},
    {STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET},
    {STREET,STREET,CAR,STREET,STREET,STREET,STREET,STREET,CAR,STREET,STREET,STREET,STREET,STREET,STREET,STREET},
    {STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET},
    {STREET,STREET,STREET,STREET,CAR,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET,STREET},
    {SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE,SAFE}
};
uint16_t puntajeactual = 0;
char puntajestring [5] = "0000";